[project]
name = "wikiapp"
version = "0.1.0"
description = "Add a short description here"
authors = [
    { name = "SGGmilagro", email = "120662824+SGGmilagro@users.noreply.github.com" },
]
requires-python = ">= 3.10"
dependencies = []

[project.scripts]
wikiapp = "wikiapp.console:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "osx-64", "win-64"]

[tool.pixi.pypi-dependencies]
wikiapp = { path = ".", editable = true }

[tool.pixi.tasks]
program = "python wikiapp/console.py"

[tool.pixi.dependencies]
requests = ">=2.31.0,<2.32"
click = ">=8.1.7,<8.2"

[tool.pixi.feature.test.dependencies]
pytest = ">=7.2.0,<8.3"
pytest-cov = ">=5.0.0,<5.1"
pytest-mock = ">=3.14.0,<3.15"

[tool.pixi.feature.test.tasks]
test = "pytest"

[tool.pixi.environments]
default = { solve-group = "default" }                   #includes defualut
test = { features = ["test"], solve-group = "default" } #includes default, test

[tool.pyright]
venvPath = "."
venv = ".pixi/envs/test"
